/* ==========================================================================
   Offshore Wind Turbine — Scroll-Driven Interactive
   Vanilla JS. Scroll position -> stage progress -> video.currentTime.
   ========================================================================== */

(function () {
  "use strict";

  /* ------------------------------------------------------------------
   * 1. HOTSPOT CONFIGURATION
   * ------------------------------------------------------------------
   * Positions are percentages (0-100) relative to the VIDEO FRAME itself
   * (the actual rendered video rectangle, accounting for its letterboxing
   * inside the container), not the browser viewport and not the outer
   * container box. They were placed against the supplied end-state
   * reference image (fully disassembled nacelle cutaway).
   *
   * To retarget a hotspot: open the end-frame image (or pause the page
   * at 100% scroll), find the component, and set x/y as a percentage of
   * the visible video frame's width/height. 0,0 is the top-left corner
   * of the video frame; 100,100 is the bottom-right corner.
   *
   * `side: "left"` flips the text label to the left of the marker, for
   * hotspots that sit near the right edge of the frame.
   * ------------------------------------------------------------------ */
  var hotspots = [
    {
      id: "rotor-hub",
      name: "Rotor & hub",
      x: 27,
      y: 57,
      what: "The three blades capture energy from the wind and transfer their rotation through the hub to the main shaft.",
      why: "This is where the wind’s kinetic energy first becomes mechanical rotation."
    },
    {
      id: "main-shaft",
      name: "Main shaft",
      x: 41,
      y: 55,
      what: "Transfers the rotational force from the rotor toward the drivetrain.",
      why: "It carries the mechanical energy captured by the blades into the machinery inside the nacelle."
    },
    {
      id: "main-bearing",
      name: "Main bearing",
      x: 48,
      y: 53,
      what: "Supports the rotating main shaft while allowing it to turn smoothly under substantial loads.",
      why: "It allows the rotor to rotate while managing the forces generated by the blades and wind."
    },
    {
      id: "gearbox",
      name: "Gearbox",
      x: 57,
      y: 53,
      what: "The gearbox increases rotational speed between the slowly rotating main shaft and the faster generator.",
      why: "The generator operates most effectively at a different rotational speed from the rotor."
    },
    {
      id: "generator",
      name: "Generator",
      x: 74,
      y: 53,
      what: "Converts mechanical rotational energy into electrical energy using electromagnetic induction.",
      why: "This is where mechanical energy becomes electrical energy.",
      side: "left"
    },
    {
      id: "power-converter",
      name: "Power converter",
      x: 81,
      y: 62,
      what: "Conditions the electrical output so it can be controlled and supplied appropriately to the electrical system.",
      why: "It helps manage the variable electrical output produced as wind conditions change.",
      side: "left"
    },
    {
      id: "transformer",
      name: "Transformer",
      x: 90,
      y: 51,
      what: "Changes the electrical voltage to a level suitable for transmission.",
      why: "Higher transmission voltage allows electricity to be transferred efficiently.",
      side: "left"
    },
    {
      id: "cooling-system",
      name: "Cooling system",
      x: 76,
      y: 36,
      what: "Removes heat generated by equipment such as the generator and power electronics.",
      why: "Keeping components within their operating temperature range helps maintain reliability.",
      side: "left"
    },
    {
      id: "yaw-system",
      name: "Yaw system",
      x: 50,
      y: 76,
      what: "Rotates the nacelle so the rotor can face the wind.",
      why: "Correct alignment helps the turbine capture wind energy effectively.",
      side: "left"
    }
  ];

  /* ------------------------------------------------------------------
   * 2. SCROLL PROGRESS -> TIMELINE MAPPING
   * ------------------------------------------------------------------ */
  var TIMELINE = {
    heroEnd: 0.08,       // hero text holds, video at 0
    discoverEnd: 0.18,   // "Inside the nacelle" label, video still ~0
    scrubStart: 0.18,
    scrubEnd: 0.86,      // video scrubs 0 -> duration across this range
    settleEnd: 0.94,     // hold final frame, swap caption -> explore copy
    hotspotsReady: 0.94  // hotspots become interactive
  };

  var CAPTIONS = [
    { at: 0.0, text: "Nacelle opening…" },
    { at: 0.22, text: "Internal machinery becoming visible…" },
    { at: 0.45, text: "Drivetrain separating…" },
    { at: 0.68, text: "Major components separating…" },
    { at: 0.92, text: "Fully disassembled." }
  ];

  var reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  /* ------------------------------------------------------------------
   * DOM refs
   * ------------------------------------------------------------------ */
  var stage = document.getElementById("stage");
  var video = document.getElementById("turbineVideo");
  var frame = document.getElementById("turbineFrame");
  var hotspotLayer = document.getElementById("hotspotLayer");

  var panelHero = document.getElementById("panelHero");
  var panelDiscover = document.getElementById("panelDiscover");
  var panelCaption = document.getElementById("panelCaption");
  var panelExplore = document.getElementById("panelExplore");
  var captionText = document.getElementById("captionText");
  var progressCount = document.getElementById("progressCount");
  var replayBtn = document.getElementById("replayBtn");
  var recapReplayBtn = document.getElementById("recapReplayBtn");
  var exploreLede = document.getElementById("exploreLede");

  var rmControls = document.getElementById("rmControls");
  var rmPlayBtn = document.getElementById("rmPlayBtn");

  var panelScrim = document.getElementById("panelScrim");
  var infoPanel = document.getElementById("infoPanel");
  var infoPanelClose = document.getElementById("infoPanelClose");
  var infoPanelEyebrow = document.getElementById("infoPanelEyebrow");
  var infoPanelTitle = document.getElementById("infoPanelTitle");
  var infoPanelWhat = document.getElementById("infoPanelWhat");
  var infoPanelWhy = document.getElementById("infoPanelWhy");
  var infoPanelPrev = document.getElementById("infoPanelPrev");
  var infoPanelNext = document.getElementById("infoPanelNext");

  var videoReady = false;
  var videoDuration = 0;
  var videoWatchdog = null;
  var hotspotsActive = false;
  var exploredIds = {};
  var selectedId = null;
  var lastFocusedEl = null;
  var hotspotEls = {};

  /* ------------------------------------------------------------------
   * 3. BUILD HOTSPOT MARKERS
   * ------------------------------------------------------------------ */
  function buildHotspots() {
    hotspots.forEach(function (h) {
      var btn = document.createElement("button");
      btn.type = "button";
      btn.className = "hotspot" + (h.side === "left" ? " hotspot--label-left" : "");
      btn.style.left = h.x + "%";
      btn.style.top = h.y + "%";
      btn.setAttribute("data-id", h.id);
      btn.setAttribute("aria-label", h.name + " — open component details");
      btn.setAttribute("aria-expanded", "false");

      var ring = document.createElement("span");
      ring.className = "hotspot__ring";
      ring.setAttribute("aria-hidden", "true");

      var label = document.createElement("span");
      label.className = "hotspot__label";
      label.textContent = h.name;

      btn.appendChild(ring);
      btn.appendChild(label);
      btn.addEventListener("click", function () {
        selectHotspot(h.id, btn);
      });

      hotspotLayer.appendChild(btn);
      hotspotEls[h.id] = btn;
    });
  }

  /* ------------------------------------------------------------------
   * 4. VIDEO FRAME <-> CONTAINER RECT (accounts for object-fit: contain)
   * ------------------------------------------------------------------
   * Hotspots are placed with left/top percentages against `.hotspot-layer`,
   * which we size and position to exactly match the visible video
   * rectangle (letterbox-corrected) inside `.turbine-frame`.
   * ------------------------------------------------------------------ */
  function syncHotspotLayerToVideo() {
    var containerW = frame.clientWidth;
    var containerH = frame.clientHeight;
    if (!containerW || !containerH) return;

    var mediaW = (video.videoWidth || 1280);
    var mediaH = (video.videoHeight || 720);
    var mediaRatio = mediaW / mediaH;
    var containerRatio = containerW / containerH;

    var renderW, renderH, offsetX, offsetY;
    if (containerRatio > mediaRatio) {
      // container wider than media -> pillarboxed (bars left/right)
      renderH = containerH;
      renderW = renderH * mediaRatio;
      offsetX = (containerW - renderW) / 2;
      offsetY = 0;
    } else {
      // container taller than media -> letterboxed (bars top/bottom)
      renderW = containerW;
      renderH = renderW / mediaRatio;
      offsetX = 0;
      offsetY = (containerH - renderH) / 2;
    }

    hotspotLayer.style.left = offsetX + "px";
    hotspotLayer.style.top = offsetY + "px";
    hotspotLayer.style.width = renderW + "px";
    hotspotLayer.style.height = renderH + "px";
  }

  /* ------------------------------------------------------------------
   * 5. SCROLL -> PROGRESS -> VIDEO SCRUB
   * ------------------------------------------------------------------ */
  var ticking = false;
  var lastProgress = -1;
  var lastCaptionIndex = -1;

  function clamp(v, min, max) {
    return Math.max(min, Math.min(max, v));
  }

  function getStageProgress() {
    var rect = stage.getBoundingClientRect();
    var total = stage.offsetHeight - window.innerHeight;
    if (total <= 0) return 1;
    var scrolled = -rect.top;
    return clamp(scrolled / total, 0, 1);
  }

  function setPanelVisible(panel, visible) {
    if (visible) {
      panel.classList.add("is-visible");
    } else {
      panel.classList.remove("is-visible");
    }
  }

  function updateFromProgress(progress) {
    if (Math.abs(progress - lastProgress) < 0.0008 && lastProgress !== -1) return;
    lastProgress = progress;

    setPanelVisible(panelHero, progress < TIMELINE.heroEnd + 0.02);
    setPanelVisible(
      panelDiscover,
      progress >= TIMELINE.heroEnd && progress < TIMELINE.scrubStart + 0.05
    );
    setPanelVisible(
      panelCaption,
      progress >= TIMELINE.scrubStart && progress < TIMELINE.settleEnd
    );
    setPanelVisible(panelExplore, progress >= TIMELINE.settleEnd);

    // caption sub-text within scrub zone
    if (progress >= TIMELINE.scrubStart && progress < TIMELINE.settleEnd) {
      var scrubProgress = clamp(
        (progress - TIMELINE.scrubStart) / (TIMELINE.scrubEnd - TIMELINE.scrubStart),
        0,
        1
      );
      var idx = 0;
      for (var i = 0; i < CAPTIONS.length; i++) {
        if (scrubProgress >= CAPTIONS[i].at) idx = i;
      }
      if (idx !== lastCaptionIndex) {
        captionText.textContent = CAPTIONS[idx].text;
        lastCaptionIndex = idx;
      }
    }

    // video scrub
    if (videoReady && videoDuration > 0) {
      var scrub = clamp(
        (progress - TIMELINE.scrubStart) / (TIMELINE.scrubEnd - TIMELINE.scrubStart),
        0,
        1
      );
      var targetTime = scrub * videoDuration;
      if (Math.abs(video.currentTime - targetTime) > 0.01) {
        try {
          video.currentTime = targetTime;
        } catch (e) {
          /* ignore seek errors during rapid scrubbing */
        }
      }
    }

    // hotspots
    var shouldBeActive = progress >= TIMELINE.hotspotsReady;
    if (shouldBeActive !== hotspotsActive) {
      hotspotsActive = shouldBeActive;
      hotspotLayer.classList.toggle("is-active", hotspotsActive);
      hotspotLayer.setAttribute("aria-hidden", hotspotsActive ? "false" : "true");
      replayBtn.hidden = !hotspotsActive;
    }
  }

  function onScroll() {
    if (ticking) return;
    ticking = true;
    requestAnimationFrame(function () {
      updateFromProgress(getStageProgress());
      ticking = false;
    });
  }

  /* ------------------------------------------------------------------
   * 6. HOTSPOT SELECTION / INFO PANEL
   * ------------------------------------------------------------------ */
  function findHotspotIndex(id) {
    for (var i = 0; i < hotspots.length; i++) {
      if (hotspots[i].id === id) return i;
    }
    return -1;
  }

  function updateProgressPill() {
    var count = Object.keys(exploredIds).length;
    progressCount.textContent = count;
    if (count >= hotspots.length) {
      exploreLede.textContent = "You’ve explored the main systems inside the nacelle.";
    }
  }

  function selectHotspot(id, triggerEl) {
    var idx = findHotspotIndex(id);
    if (idx === -1) return;
    var data = hotspots[idx];

    selectedId = id;
    exploredIds[id] = true;
    updateProgressPill();

    Object.keys(hotspotEls).forEach(function (key) {
      hotspotEls[key].classList.toggle("is-selected", key === id);
      hotspotEls[key].setAttribute("aria-expanded", key === id ? "true" : "false");
      if (exploredIds[key]) hotspotEls[key].classList.add("is-explored");
    });
    hotspotLayer.classList.add("is-dimmed");

    infoPanelEyebrow.textContent = "Component " + (idx + 1) + " of " + hotspots.length;
    infoPanelTitle.textContent = data.name;
    infoPanelWhat.textContent = data.what;
    infoPanelWhy.textContent = data.why;

    lastFocusedEl = triggerEl || hotspotEls[id];
    openInfoPanel();
  }

  function openInfoPanel() {
    infoPanel.hidden = false;
    panelScrim.hidden = false;
    requestAnimationFrame(function () {
      infoPanel.classList.add("is-visible");
      panelScrim.classList.add("is-visible");
    });
    infoPanelClose.focus();
    document.addEventListener("keydown", onPanelKeydown);
  }

  function closeInfoPanel() {
    infoPanel.classList.remove("is-visible");
    panelScrim.classList.remove("is-visible");
    hotspotLayer.classList.remove("is-dimmed");
    Object.keys(hotspotEls).forEach(function (key) {
      hotspotEls[key].classList.remove("is-selected");
      hotspotEls[key].setAttribute("aria-expanded", "false");
    });
    document.removeEventListener("keydown", onPanelKeydown);
    setTimeout(function () {
      if (!infoPanel.classList.contains("is-visible")) {
        infoPanel.hidden = true;
        panelScrim.hidden = true;
      }
    }, 320);
    if (lastFocusedEl) lastFocusedEl.focus();
    selectedId = null;
  }

  function onPanelKeydown(e) {
    if (e.key === "Escape") {
      closeInfoPanel();
    }
  }

  function stepHotspot(dir) {
    if (!selectedId) return;
    var idx = findHotspotIndex(selectedId);
    var nextIdx = (idx + dir + hotspots.length) % hotspots.length;
    var nextId = hotspots[nextIdx].id;
    selectHotspot(nextId, hotspotEls[nextId]);
  }

  /* ------------------------------------------------------------------
   * 7. REPLAY
   * ------------------------------------------------------------------ */
  function replayDisassembly() {
    if (!infoPanel.hidden) closeInfoPanel();
    var top = stage.offsetTop;
    window.scrollTo({ top: top + 4, behavior: reduceMotion ? "auto" : "smooth" });
  }

  /* ------------------------------------------------------------------
   * 8. REDUCED MOTION MODE
   * ------------------------------------------------------------------ */
  function initReducedMotion() {
    rmControls.hidden = false;

    setPanelVisible(panelHero, true);
    setPanelVisible(panelExplore, true);
    setPanelVisible(panelDiscover, false);
    setPanelVisible(panelCaption, false);

    hotspotLayer.classList.add("is-active");
    hotspotLayer.setAttribute("aria-hidden", "false");
    hotspotsActive = true;
    replayBtn.hidden = false;

    function showFinalFrame() {
      if (videoDuration > 0) {
        video.currentTime = videoDuration;
      }
    }

    if (video.readyState >= 1) {
      showFinalFrame();
    } else {
      video.addEventListener("loadedmetadata", showFinalFrame, { once: true });
    }

    rmPlayBtn.addEventListener("click", function () {
      video.currentTime = 0;
      video.play().catch(function () {});
    });

    video.addEventListener("ended", showFinalFrame);

    replayBtn.addEventListener("click", function () {
      video.currentTime = 0;
      video.play().catch(function () {});
    });
    recapReplayBtn.addEventListener("click", function () {
      video.currentTime = 0;
      video.play().catch(function () {});
      window.scrollTo({ top: stage.offsetTop, behavior: "auto" });
    });
  }

  /* ------------------------------------------------------------------
   * 9. INIT
   * ------------------------------------------------------------------ */
  function init() {
    buildHotspots();

    // Apply the reduced-motion layout class before measuring the frame,
    // so the hotspot layer syncs against final (not pre-layout) geometry.
    if (reduceMotion) {
      document.body.classList.add("reduced-motion");
    }

    // Metadata may ALREADY be available by the time this runs — with an
    // inlined/data-URI source the browser can parse it before the script
    // executes, and a `loadedmetadata` listener attached afterwards would
    // never fire. Always check readyState first, then listen as a fallback.
    function onVideoMetadata() {
      if (videoReady) return;
      videoReady = true;
      videoDuration = video.duration || 0;
      clearTimeout(videoWatchdog);
      syncHotspotLayerToVideo();
      paintFirstFrame();
      if (!reduceMotion) updateFromProgress(getStageProgress());
    }

    if (video.readyState >= 1) {
      onVideoMetadata();
    } else {
      video.addEventListener("loadedmetadata", onVideoMetadata);
    }

    // A video that has never been seeked or played renders nothing at all.
    // At scroll 0 the target time is 0, so the normal scrub guard is a
    // no-op and the element would stay blank — nudge it off zero once so
    // the browser decodes and paints an actual first frame.
    function paintFirstFrame() {
      try {
        video.currentTime = 0.04;
      } catch (e) {
        /* seek unsupported; the still image underneath remains visible */
      }
    }

    // If the video never becomes usable (blocked source, unsupported
    // codec), leave the still image showing rather than a blank stage.
    videoWatchdog = setTimeout(function () {
      if (!videoReady) frame.classList.add("is-video-unavailable");
    }, 8000);

    video.addEventListener("error", function () {
      clearTimeout(videoWatchdog);
      frame.classList.add("is-video-unavailable");
    });

    window.addEventListener("resize", function () {
      syncHotspotLayerToVideo();
      if (!reduceMotion) updateFromProgress(getStageProgress());
    });
    syncHotspotLayerToVideo();

    infoPanelClose.addEventListener("click", closeInfoPanel);
    panelScrim.addEventListener("click", closeInfoPanel);
    infoPanelPrev.addEventListener("click", function () { stepHotspot(-1); });
    infoPanelNext.addEventListener("click", function () { stepHotspot(1); });

    if (reduceMotion) {
      initReducedMotion();
    } else {
      window.addEventListener("scroll", onScroll, { passive: true });
      updateFromProgress(getStageProgress());

      replayBtn.addEventListener("click", replayDisassembly);
      recapReplayBtn.addEventListener("click", replayDisassembly);
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
